### PR TITLE
fix changebank logo

### PR DESCRIPTION
**Pull request by escii**
fixed changebank logo, added multiplattform font definitions.

### CODE REVIEW

**Comment by escii** [comment]
@mooreds please review

**Comment by mooreds** [comment]
@escii what is the root issue this addresses? I can't find the GH issue for it, but I remember seeing it. Please link it here.

**Comment by escii** [comment]
@mooreds Issue: https://github.com/FusionAuth/fusionauth-issues/issues/2422
please don't close #2422, I need to apply that fix for some other repos too.

**Comment by ColinFrick** [comment]
@mooreds This PR also adds the missing Make Change page

**Pull request merged**
